### ISSUE TITLE
Feature request: backgrounding mode

### ISSUE THREAD

**Issue by zoobab** [julman99/eatmemory#7]
Hi,

Would it be possible to go in background mode and do not read the input from the tty?

For the dockerization, it would be better if there is only one process inside that gets killed if it cannot allocate the memory, or being killed by the linux kernel.

Or maybe an argument to like "-d" to go in daemon mode...

Best,

**Comment by julman99** [comment]
Love it, will do this (along with your other suggestion) before the weekend ends

**Comment by julman99** [comment]
Changes done, if no tty is detected, `eatmemory` will run forever until killed
