### ISSUE TITLE
Conflicting options: --rm and -d

### ISSUE THREAD

**Issue by zoobab** [julman99/eatmemory#8]
Hi,

When I try to run the last example:

$ docker run -d --rm --name hungry_container julman99/eatmemory 128M
Conflicting options: --rm and -d

Do you have the same problem?

**Comment by julman99** [comment]
No, what docker version are you running?

**Comment by zoobab** [comment]
1.12.3

**Comment by julman99** [comment]
I might be because of that, that version if from the end of 2016. Can you try upgrading?

**Comment by zoobab** [comment]
Yeah it is, I tried with a docker-in-docker in version 17.05, it works, but not in 1.12.3. It seems they changed the behaviour.
